name: Auto Update GitHub Overview (Hidden)

on:
  schedule:
    - cron: "0 6 * * *"   # 03:00 Argentina (UTC-3)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update hidden timestamp in README
        run: |
          TS="<!-- last-update: $(date -u +'%Y-%m-%dT%H:%M:%SZ') -->"
          # reemplaza si existe; si no, agrega al final
          if grep -q "<!-- last-update:" README.md; then
            sed -i "s/<!-- last-update: .* -->/$TS/" README.md
          else
            echo "" >> README.md
            echo "$TS" >> README.md
          fi

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-refresh (hidden timestamp)" || echo "No changes to commit"
          git push
