name: Manual Update GitHub Overview

on:
  workflow_dispatch:   

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Touch README to force profile refresh
        run: |
          echo "<!-- manual-refresh: $(date -u) -->" >> README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Manual refresh of GitHub overview" || echo "No changes to commit"
          git push
