name: Update GitHub Stats
on:
  schedule:
    - cron: "0 * * * *"   # Ejecuta cada hora
  workflow_dispatch:       # Ejecución manual o no

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh GitHub Stats Cache
        run: |
          curl -s -o /dev/null "https://github-readme-stats.vercel.app/api?username=tomasgz7&count_private=true&v=$(date +%s)"
